### ISSUE TITLE
Marlin_main.cpp diff

### ISSUE THREAD

**Issue by dannen** [NNatsios/nanoBean#1]
I noticed that the firmware from Kudo has a big chunk of code that yours is missing.  I don't know if they added it after shipping or what, figured you'd want to look at it.

(https://www.dropbox.com/s/ip16h077z7pdajg/Bean_mega2560_firmware_20181015.zip?dl=0)

https://www.diffchecker.com/mkDt4UFr

Starts around line 1197.

**Comment by ltaylorwarren** [comment]
Very interested in everyone's thoughts on this.  I installed the NanoDLP image on a microSD card last night and have done everything except the firmware update to the mega2560.  I was just about to attempt the install when I saw this message. Are the missing blocks of code important to the long term stability of the bean?  Can I safely merge the two differences to a new marlin_main.cpp file and place it in the folder prior to using the IDE to update the board?

**Comment by dannen** [comment]
well, its been running safely without it so I assume its more of a feature add than a bugfix.  The code is identical in all three places and appears to be an emergency retract option.  AFAIK it's never actually called in the code, so it must be called by something external aka octoprint/nanodlp. 

Now that I'm digging around, I see a reference here:

http://marlinfw.org/docs/gcode/M207.html

Which would seem to indicate it is for retracting the filament in an FDM printer.  This is completely useless to our SLA printing so I'm going to say its not necessary and close this issue.  I should have dug some more first. ;)
